/**
 * Reclaimable locations outside language ecosystems: browser binaries for
 * test runners, IDE caches, AI agent stores, OS package caches, Trash, and
 * leftovers in temporary directories.
 *
 * `scope` selects how paths expand:
 * - `home` (default): `~` is every home directory;
 * - `system`: absolute paths, checked a single time per environment;
 * - `tmp`: `{TMP}` is every temporary directory (`/tmp`, `$TMPDIR`).
 *
 * `aggregate: true` reports all matches of the rule as a single item,
 * otherwise each match is its own item. `minAge: 'stale'` only reports
 * matches untouched for the stale-age window, `minAge: 'inactive'` for the
 * project inactivity window. `git: true` refuses matches that are Git work
 * trees with uncommitted, unpushed, or stashed changes.
 */

export const OTHER_RULES = [
  {
    id: 'playwright-browsers',
    ecosystem: 'browsers',
    description: 'old Playwright browser revisions',
    paths: [
      '~/.cache/ms-playwright/*',
      '~/Library/Caches/ms-playwright/*',
      '{LOCALAPPDATA}/ms-playwright/*',
    ],
    versionPattern: /^(?<family>[a-z_]+)-(?<version>\d+)$/,
    minAge: 'inactive',
    tier: 'moderate',
    busy: [
      'playwright',
      'playwright-mcp',
      'chrome',
      'chromium',
      'headless_shell',
      'firefox',
      'webkit',
    ],
  },
  {
    id: 'playwright-go-drivers',
    ecosystem: 'browsers',
    description: 'old playwright-go driver versions',
    paths: [
      '~/.cache/ms-playwright-go/*',
      '~/Library/Caches/ms-playwright-go/*',
      '{LOCALAPPDATA}/ms-playwright-go/*',
    ],
    versionPattern: /^(?<version>\d+(?:\.\d+){1,3})$/,
    minAge: 'inactive',
    tier: 'moderate',
    busy: ['playwright'],
  },
  {
    id: 'puppeteer-browsers',
    ecosystem: 'browsers',
    description: 'old Puppeteer browser revisions',
    paths: ['~/.cache/puppeteer/*/*'],
    versionPattern: /^(?<family>[a-z0-9_-]+)-(?<version>\d[\d.]*)$/,
    minAge: 'inactive',
    tier: 'moderate',
    busy: ['puppeteer', 'chrome', 'chromium', 'headless_shell'],
  },
  {
    id: 'cypress-binaries',
    ecosystem: 'browsers',
    description: 'old Cypress binary revisions',
    paths: ['~/.cache/Cypress/*', '~/Library/Caches/Cypress/*'],
    versionPattern: /^(?<version>\d+(?:\.\d+){1,3})$/,
    minAge: 'inactive',
    tier: 'moderate',
    busy: ['Cypress', 'cypress'],
  },
  {
    id: 'selenium-drivers',
    ecosystem: 'browsers',
    description: 'old Selenium Manager driver revisions',
    paths: ['~/.cache/selenium/*/*/*'],
    versionPattern: /^(?<version>\d+(?:\.\d+){1,3})$/,
    minAge: 'inactive',
    tier: 'moderate',
    busy: ['chromedriver', 'geckodriver'],
  },
  {
    id: 'jetbrains-caches',
    ecosystem: 'ide',
    description: 'JetBrains IDE caches, indexes and logs',
    paths: [
      '~/.cache/JetBrains',
      '~/Library/Caches/JetBrains',
      '~/Library/Logs/JetBrains',
      '{LOCALAPPDATA}/JetBrains/*/caches',
    ],
    busy: ['idea', 'pycharm', 'webstorm', 'clion', 'goland', 'rider', 'java'],
  },
  {
    id: 'vscode-caches',
    ecosystem: 'ide',
    description: 'VS Code caches and downloaded extension packages',
    paths: [
      '~/.config/Code/Cache',
      '~/.config/Code/CachedData',
      '~/.config/Code/CachedExtensionVSIXs',
      '~/.config/Code/logs',
      '~/Library/Application Support/Code/Cache',
      '~/Library/Application Support/Code/CachedData',
      '~/Library/Application Support/Code/CachedExtensionVSIXs',
      '~/.vscode-server/data/CachedExtensionVSIXs',
      '~/.vscode-server/data/logs',
      '~/.cursor-server/data/CachedExtensionVSIXs',
    ],
    busy: ['code', 'Code', 'code-server', 'cursor'],
  },
  {
    id: 'vscode-fork-caches',
    ecosystem: 'ide',
    description:
      'Cursor, Windsurf and Qoder caches and downloaded extension packages',
    paths: [
      '~/.config/Cursor/Cache',
      '~/.config/Cursor/CachedData',
      '~/.config/Cursor/CachedExtensionVSIXs',
      '~/.config/Windsurf/Cache',
      '~/.config/Windsurf/CachedData',
      '~/.config/Windsurf/CachedExtensionVSIXs',
      '~/Library/Application Support/Cursor/Cache',
      '~/Library/Application Support/Cursor/CachedData',
      '~/Library/Application Support/Cursor/CachedExtensionVSIXs',
      '~/Library/Application Support/Windsurf/Cache',
      '~/Library/Application Support/Windsurf/CachedData',
      '~/Library/Application Support/Windsurf/CachedExtensionVSIXs',
      '~/Library/Application Support/Qoder/Cache',
      '~/Library/Application Support/Qoder/CachedData',
      '~/Library/Application Support/Qoder/CachedExtensionVSIXs',
      '{APPDATA}/Cursor/Cache',
      '{APPDATA}/Cursor/CachedData',
      '{APPDATA}/Cursor/CachedExtensionVSIXs',
      '{APPDATA}/Windsurf/Cache',
      '{APPDATA}/Windsurf/CachedData',
      '{APPDATA}/Windsurf/CachedExtensionVSIXs',
      '{APPDATA}/Qoder/Cache',
      '{APPDATA}/Qoder/CachedData',
      '{APPDATA}/Qoder/CachedExtensionVSIXs',
    ],
    busy: ['cursor', 'Cursor', 'windsurf', 'Windsurf', 'Qoder'],
  },
  {
    id: 'discord-cache',
    ecosystem: 'apps',
    description: 'Discord HTTP cache',
    paths: [
      '~/.config/discord/Cache',
      '~/Library/Application Support/discord/Cache',
      '{APPDATA}/discord/Cache',
    ],
    busy: ['Discord', 'discord'],
  },
  {
    id: 'chrome-http-caches',
    ecosystem: 'browsers',
    description: 'Chrome and Chromium HTTP and compiled-code caches',
    paths: [
      '~/.cache/google-chrome/*/Cache',
      '~/.config/google-chrome/*/Code Cache',
      '~/.cache/chromium/*/Cache',
      '~/.config/chromium/*/Code Cache',
      '~/Library/Caches/Google/Chrome/*/Cache',
      '~/Library/Caches/Google/Chrome/*/Code Cache',
      '~/Library/Caches/Chromium/*/Cache',
      '~/Library/Caches/Chromium/*/Code Cache',
      '{LOCALAPPDATA}/Google/Chrome/User Data/*/Cache',
      '{LOCALAPPDATA}/Google/Chrome/User Data/*/Code Cache',
      '{LOCALAPPDATA}/Chromium/User Data/*/Cache',
      '{LOCALAPPDATA}/Chromium/User Data/*/Code Cache',
    ],
    busy: ['Google Chrome', 'chrome', 'Chromium', 'chromium'],
  },
  {
    id: 'edge-http-caches',
    ecosystem: 'browsers',
    description: 'Microsoft Edge HTTP and compiled-code caches',
    paths: [
      '~/.cache/microsoft-edge/*/Cache',
      '~/.config/microsoft-edge/*/Code Cache',
      '~/Library/Caches/Microsoft Edge/*/Cache',
      '~/Library/Caches/Microsoft Edge/*/Code Cache',
      '{LOCALAPPDATA}/Microsoft/Edge/User Data/*/Cache',
      '{LOCALAPPDATA}/Microsoft/Edge/User Data/*/Code Cache',
    ],
    busy: ['Microsoft Edge', 'msedge'],
  },
  {
    id: 'brave-http-caches',
    ecosystem: 'browsers',
    description: 'Brave HTTP and compiled-code caches',
    paths: [
      '~/.cache/BraveSoftware/Brave-Browser/*/Cache',
      '~/.config/BraveSoftware/Brave-Browser/*/Code Cache',
      '~/Library/Caches/BraveSoftware/Brave-Browser/*/Cache',
      '~/Library/Caches/BraveSoftware/Brave-Browser/*/Code Cache',
      '{LOCALAPPDATA}/BraveSoftware/Brave-Browser/User Data/*/Cache',
      '{LOCALAPPDATA}/BraveSoftware/Brave-Browser/User Data/*/Code Cache',
    ],
    busy: ['Brave Browser', 'brave'],
  },
  {
    // Opera keeps a single profile: its caches sit at the top of its folders.
    id: 'opera-http-caches',
    ecosystem: 'browsers',
    description: 'Opera and Opera GX HTTP and compiled-code caches',
    paths: [
      '~/.cache/opera/Cache',
      '~/.config/opera/Code Cache',
      '~/Library/Caches/com.operasoftware.Opera/Cache',
      '~/Library/Caches/com.operasoftware.Opera/Code Cache',
      '~/Library/Caches/com.operasoftware.OperaGX/Cache',
      '~/Library/Caches/com.operasoftware.OperaGX/Code Cache',
      '{LOCALAPPDATA}/Opera Software/Opera Stable/Cache',
      '{LOCALAPPDATA}/Opera Software/Opera Stable/Code Cache',
      '{LOCALAPPDATA}/Opera Software/Opera GX Stable/Cache',
      '{LOCALAPPDATA}/Opera Software/Opera GX Stable/Code Cache',
    ],
    busy: ['Opera', 'opera', 'Opera GX'],
  },
  {
    id: 'vivaldi-http-caches',
    ecosystem: 'browsers',
    description: 'Vivaldi HTTP and compiled-code caches',
    paths: [
      '~/.cache/vivaldi/*/Cache',
      '~/.config/vivaldi/*/Code Cache',
      '~/Library/Caches/Vivaldi/*/Cache',
      '~/Library/Caches/Vivaldi/*/Code Cache',
      '{LOCALAPPDATA}/Vivaldi/User Data/*/Cache',
      '{LOCALAPPDATA}/Vivaldi/User Data/*/Code Cache',
    ],
    busy: ['Vivaldi', 'vivaldi', 'vivaldi-bin'],
  },
  {
    id: 'arc-http-caches',
    ecosystem: 'browsers',
    description: 'Arc HTTP and compiled-code caches',
    paths: [
      '~/Library/Caches/Arc/User Data/*/Cache',
      '~/Library/Caches/Arc/User Data/*/Code Cache',
    ],
    busy: ['Arc'],
  },
  {
    id: 'whale-http-caches',
    ecosystem: 'browsers',
    description: 'Naver Whale HTTP and compiled-code caches',
    paths: [
      '~/.cache/naver-whale/*/Cache',
      '~/.config/naver-whale/*/Code Cache',
      '~/Library/Caches/Naver/Whale/*/Cache',
      '~/Library/Caches/Naver/Whale/*/Code Cache',
      '{LOCALAPPDATA}/Naver/Naver Whale/User Data/*/Cache',
      '{LOCALAPPDATA}/Naver/Naver Whale/User Data/*/Code Cache',
    ],
    busy: ['Whale', 'whale', 'Naver Whale'],
  },
  {
    id: 'chinese-chromium-http-caches',
    ecosystem: 'browsers',
    description: '360 and QQ Browser HTTP and compiled-code caches',
    paths: [
      '{LOCALAPPDATA}/360Chrome/Chrome/User Data/*/Cache',
      '{LOCALAPPDATA}/360Chrome/Chrome/User Data/*/Code Cache',
      '{APPDATA}/360se6/User Data/*/Cache',
      '{APPDATA}/360se6/User Data/*/Code Cache',
      '{LOCALAPPDATA}/Tencent/QQBrowser/User Data/*/Cache',
      '{LOCALAPPDATA}/Tencent/QQBrowser/User Data/*/Code Cache',
    ],
    busy: ['360chrome', '360se', 'QQBrowser'],
  },
  {
    id: 'yandex-browser-http-caches',
    ecosystem: 'browsers',
    description: 'Yandex Browser HTTP and compiled-code caches',
    paths: [
      '~/.cache/yandex-browser/*/Cache',
      '~/.config/yandex-browser/*/Code Cache',
      '~/Library/Caches/Yandex/YandexBrowser/*/Cache',
      '~/Library/Caches/Yandex/YandexBrowser/*/Code Cache',
      '{LOCALAPPDATA}/Yandex/YandexBrowser/User Data/*/Cache',
      '{LOCALAPPDATA}/Yandex/YandexBrowser/User Data/*/Code Cache',
    ],
    busy: ['Yandex', 'yandex_browser'],
  },
  {
    id: 'firefox-http-caches',
    ecosystem: 'browsers',
    description: 'Firefox HTTP cache',
    paths: [
      '~/.cache/mozilla/firefox/*/cache2',
      '~/Library/Caches/Firefox/Profiles/*/cache2',
      '{LOCALAPPDATA}/Mozilla/Firefox/Profiles/*/cache2',
    ],
    busy: ['firefox', 'Firefox'],
  },
  {
    id: 'firefox-fork-http-caches',
    ecosystem: 'browsers',
    description: 'LibreWolf, Waterfox, Zen and Floorp HTTP caches',
    paths: [
      '~/.cache/librewolf/*/cache2',
      '~/.cache/waterfox/*/cache2',
      '~/.cache/zen/*/cache2',
      '~/.cache/floorp/*/cache2',
      '~/Library/Caches/librewolf/Profiles/*/cache2',
      '~/Library/Caches/Waterfox/Profiles/*/cache2',
      '~/Library/Caches/zen/Profiles/*/cache2',
      '~/Library/Caches/Floorp/Profiles/*/cache2',
      '{LOCALAPPDATA}/librewolf/Profiles/*/cache2',
      '{LOCALAPPDATA}/Waterfox/Profiles/*/cache2',
      '{LOCALAPPDATA}/zen/Profiles/*/cache2',
      '{LOCALAPPDATA}/Floorp/Profiles/*/cache2',
    ],
    busy: [
      'librewolf',
      'LibreWolf',
      'waterfox',
      'Waterfox',
      'zen',
      'Zen',
      'floorp',
      'Floorp',
    ],
  },
  {
    id: 'copilot-caches',
    ecosystem: 'ide',
    description: 'GitHub Copilot language server logs and caches',
    paths: ['~/.cache/github-copilot', '~/.config/github-copilot/logs'],
    busy: ['copilot-language-server', 'code'],
  },
  {
    id: 'codex-logs',
    ecosystem: 'agents',
    description: 'Codex CLI logs',
    paths: ['~/.codex/log'],
    busy: ['codex'],
  },
  {
    id: 'codex-runtime-staging',
    ecosystem: 'agents',
    description: 'abandoned Codex runtime install staging directories',
    paths: ['~/.cache/codex-runtimes/codex-runtime-install-*'],
    minAge: 'stale',
    busy: ['codex'],
  },
  {
    id: 'claude-cli-mcp-logs',
    ecosystem: 'agents',
    description: 'Claude Code MCP server logs, one directory per project',
    aggregate: true,
    paths: [
      '~/.cache/claude-cli-nodejs/*',
      '~/Library/Caches/claude-cli-nodejs/*',
      '{LOCALAPPDATA}/claude-cli-nodejs/Cache/*',
    ],
    minAge: 'stale',
  },
  {
    id: 'homebrew-cache',
    ecosystem: 'system',
    description: 'Homebrew download cache',
    paths: ['~/Library/Caches/Homebrew', '~/.cache/Homebrew'],
    busy: ['brew'],
  },
  {
    id: 'sparkle-update-downloads',
    ecosystem: 'system',
    description:
      'macOS app updates downloaded by Sparkle, re-downloaded by the next update check',
    paths: ['~/Library/Caches/*/org.sparkle-project.Sparkle'],
    minAge: 'stale',
    busy: ['Autoupdate', 'Installer'],
  },
  {
    id: 'shipit-update-downloads',
    ecosystem: 'system',
    description:
      'Electron app updates downloaded by Squirrel (ShipIt), re-downloaded by the next update check',
    paths: ['~/Library/Caches/*.ShipIt/update.*'],
    minAge: 'stale',
    busy: ['ShipIt'],
  },
  {
    id: 'trash',
    ecosystem: 'system',
    description: 'Trash contents',
    tier: 'moderate',
    aggregate: true,
    paths: [
      '~/.local/share/Trash/files',
      '~/.local/share/Trash/info',
      '~/.Trash/*',
    ],
  },
  {
    id: 'user-crash-reports',
    ecosystem: 'system',
    description: 'macOS crash and diagnostic reports',
    tier: 'moderate',
    aggregate: true,
    paths: ['~/Library/Logs/DiagnosticReports/*'],
  },
  {
    id: 'apt-archives',
    ecosystem: 'system',
    scope: 'system',
    description: 'apt downloaded packages',
    aggregate: true,
    paths: ['/var/cache/apt/archives/*.deb', '/var/cache/apt/*.bin'],
    native: { tool: 'apt-get', argv: ['apt-get', 'clean'], root: true },
    busy: ['apt', 'apt-get', 'dpkg', 'unattended-upgr'],
  },
  {
    id: 'dnf-yum-cache',
    ecosystem: 'system',
    scope: 'system',
    description: 'dnf/yum metadata and package cache',
    paths: ['/var/cache/dnf', '/var/cache/yum'],
    native: { tool: 'dnf', argv: ['dnf', 'clean', 'all'], root: true },
    busy: ['dnf', 'yum', 'rpm'],
  },
  {
    id: 'pacman-cache',
    ecosystem: 'system',
    scope: 'system',
    description: 'pacman package cache (used for downgrades)',
    tier: 'moderate',
    aggregate: true,
    paths: ['/var/cache/pacman/pkg/*'],
    busy: ['pacman', 'yay', 'paru'],
  },
  {
    id: 'apk-cache',
    ecosystem: 'system',
    scope: 'system',
    description: 'Alpine apk cache',
    aggregate: true,
    paths: ['/var/cache/apk/*'],
    busy: ['apk'],
  },
  {
    id: 'snapd-cache',
    ecosystem: 'system',
    scope: 'system',
    description: 'snapd download cache',
    aggregate: true,
    paths: ['/var/lib/snapd/cache/*'],
    busy: ['snap'],
  },
  {
    id: 'core-dumps',
    ecosystem: 'system',
    scope: 'system',
    description: 'core dumps and crash reports',
    tier: 'moderate',
    aggregate: true,
    paths: ['/var/lib/systemd/coredump/*', '/var/crash/*', '/cores/*'],
  },
  {
    id: 'gh-issue-solver-workdirs',
    ecosystem: 'tmp',
    scope: 'tmp',
    description: 'abandoned hive-mind solver working copies',
    tier: 'moderate',
    paths: ['{TMP}/gh-issue-solver-*'],
    minAge: 'stale',
    git: true,
    busy: ['claude', 'codex', 'opencode', 'agent', 'git', 'node', 'bun'],
  },
  {
    id: 'browser-tmp-profiles',
    ecosystem: 'tmp',
    scope: 'tmp',
    description: 'leftover headless browser profiles',
    paths: [
      '{TMP}/puppeteer_dev_chrome_profile-*',
      '{TMP}/playwright_chromiumdev_profile-*',
      '{TMP}/playwright-artifacts-*',
      '{TMP}/.org.chromium.Chromium.*',
    ],
    minAge: 'stale',
    busy: ['chrome', 'chromium', 'headless_shell'],
  },
  {
    id: 'node-tmp-caches',
    ecosystem: 'tmp',
    scope: 'tmp',
    description: 'Node.js compile caches in temporary directories',
    paths: [
      '{TMP}/node-compile-cache',
      '{TMP}/v8-compile-cache-*',
      '{TMP}/jiti',
    ],
    minAge: 'stale',
    busy: ['node'],
  },
];
